### ISSUE TITLE
May come across PHP warning

### ISSUE THREAD

**Issue by hazuremon** [Cynthiad215/ubc-rest-post-meta#3]
https://github.com/Cynthiad215/ubc-rest-post-meta/blob/2833e8e29c6ccf3fc3340b51cbdf923f787af48f/ubc-rest-post-meta.php#L44

If the key has not been declared, this may potentially lead to warning. Use isset() first to check if the key is set in addition to empty()

**Comment by cynthiade** [comment]
Updated to check that key is set
